app:
  base-url: "${APP_HOST:http://localhost:4200}"
  crypto-secret: "${APP_CRYPTO_SECRET}"
  mail: "${APP_MAIL_SERVICE:AWSSES}"
  root-email: "${APP_ROOT_EMAIL:}"
  covers-dir: "${APP_COVERS_DIR:covers}"